# Generated by Django 3.2.5 on 2021-08-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('availablecolours', models.CharField(max_length=10)),
                ('contactnumber', models.IntegerField()),
                ('emailid', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('NameOfOccasion', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('typeofcake', models.CharField(max_length=100)),
                ('byprice', models.CharField(max_length=100)),
            ],
        ),
    ]
